language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
   - "3.6"
services:
  - docker

before_install:
  - docker pull rvygon/envdocker
   
script:
 
  - docker run -ti -v `pwd`:/tmp --rm rvygon/envdocker /bin/bash -c "source activate test_z ;  jupyter nbconvert --to html /tmp/CityScapesRV.ipynb
